# ----
# Site

title: Chronos
url: "https://chronos-eaas.org"
baseurl: 
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: "The Swiss Army Knife for Systems Evaluations"
author:
  name: "DBIS, University of Basel"
  email:
  twitter: # twitter username without the @ symbol
social:
  name: GitHub
  links:
    - https://github.com/Chronos-EaaS/

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
